[package]
name = "marknote"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "path-all", "window-create", "dialog-all", "window-maximize", "window-minimize", "window-unminimize", "window-hide", "window-close", "window-start-dragging", "window-unmaximize", "window-show", "os-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pulldown-cmark="0.9.3"


window-shadows = "0.2.1"
#[target.'cfg(windows)'.dependencies]
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
