name: Release
 
on:
  push:
    tags:
      - 'v*'
 
jobs:
  macos-release:
    permissions:
        contents: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
      - run: yarn
 
      - name: Build Tauri
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}
        with:
          args: --target ${{matrix.arch}}
          tagName: v__VERSION__
          releaseName: v__VERSION__
  windows-release:
    permissions:
        contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: yarn
  
      - name: Build Tauri
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
  linux-release:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y javascriptcoregtk-4.1 libgtk-3-dev webkit2gtk-4.1 libappindicator3-dev librsvg2-dev patchelf
      - run: yarn
  
      - name: Build Tauri
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
  update:
    permissions:
        contents: write
    needs: [macos-release,windows-release,linux-release]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
 
      - run: yarn
 
      - name: Create Update
        run: yarn update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}